In [6]:
import numpy as np

# create two random arrays of the same size
x = np.random.rand(5)
y = np.random.rand(5)

print(x)
print(y)

from scipy.spatial.distance import cdist
from sentence_transformers import util

# compute the cosine distance between the two arrays using cdist
cosine_distance = 1 - cdist(x[:, None], y[:, None], metric='cosine')
print(cosine_distance)

# compute the cosine distance between the two arrays using sentence_transformers
cosine_distance_st = util.pytorch_cos_sim(x[:, None], y[:, None])
print(cosine_distance_st)

print(np.allclose(cosine_distance, cosine_distance_st.cpu().numpy()))


[0.61635501 0.47326762 0.87696553 0.23840527 0.53291692]
[0.52412417 0.71245148 0.4799476  0.75362221 0.93728032]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
True


In [9]:
import numpy as np
from scipy.spatial.distance import cdist
from sentence_transformers import util

# Create two random 2D arrays of shape (5, 10) to have more than one dimension
x = np.random.rand(5, 10)
y = np.random.rand(5, 10)

# Compute the cosine distance between the two arrays using cdist
cosine_distance = cdist(x, y, metric='cosine')

# Convert cosine distance to cosine similarity
cosine_similarity_cdist = 1 - cosine_distance

# Compute the cosine similarity between the two arrays using sentence_transformers
cosine_similarity_st = util.pytorch_cos_sim(x, y)

# Print the results
print("Cosine similarity using scipy's cdist:\n", cosine_similarity_cdist)
print("Cosine similarity using sentence_transformers' pytorch_cos_sim:\n", cosine_similarity_st)

# Compare the results
comparison = np.isclose(cosine_similarity_cdist, cosine_similarity_st.numpy(), atol=1e-6)
print("Are the results approximately equal?\n", comparison.all())


Cosine similarity using scipy's cdist:
 [[0.76785282 0.72877287 0.73773856 0.68076054 0.57399827]
 [0.61634297 0.74934921 0.96000236 0.96592665 0.75205659]
 [0.5885976  0.87679951 0.67979463 0.78676642 0.6989256 ]
 [0.7576953  0.78866301 0.73402599 0.82553025 0.67465421]
 [0.53237274 0.81621932 0.6576293  0.68680345 0.61133636]]
Cosine similarity using sentence_transformers' pytorch_cos_sim:
 tensor([[0.7679, 0.7288, 0.7377, 0.6808, 0.5740],
        [0.6163, 0.7493, 0.9600, 0.9659, 0.7521],
        [0.5886, 0.8768, 0.6798, 0.7868, 0.6989],
        [0.7577, 0.7887, 0.7340, 0.8255, 0.6747],
        [0.5324, 0.8162, 0.6576, 0.6868, 0.6113]], dtype=torch.float64)
Are the results approximately equal?
 True


In [11]:
# create a dataframe with some random text
import pandas as pd

df = pd.read_csv('/Users/datoapanta/Desktop/autopop/context-match/databases/Locations - Netherlands.csv')
print(df['Municipality'].astype(str).tolist())

['Zwolle', 'Zwartewaterland', 'Zwijndrecht', 'Zuidplas', 'Zutphen', 'Zundert', 'Zevenaar', 'Zeist', 'Zoeterwoude', 'Zoetermeer', 'Zandvoort', 'Zeewolde', 'Zaltbommel', 'Woerden', 'Woudenberg', 'Zaanstad', 'Wormerland', 'Winterswijk', 'Woensdrecht', 'Wijk bij Duurstede', 'Wijdemeren', 'Wijchen', 'Weststellingwerf', 'Wierden', 'Westerveld', 'Westervoort', 'Westerwolde', 'Westland', 'Weert', 'West Maas en Waal', 'Westerkwartier', 'West Betuwe', 'Wassenaar', 'Waterland', 'Wageningen', 'Waddinxveen', 'Waalwijk', 'Waadhoeke', 'Waalre', 'Voorst', 'Voorschoten', 'Vught', 'Vlieland', 'Voerendaal', 'Voorne aan Zee', 'Vlissingen', 'Vijfheerenlanden', 'Venray', 'Vlaardingen', 'Veere', 'Venlo', 'Velsen', 'Veldhoven', 'Veendam', 'Valkenswaard', 'Veenendaal', 'Valkenburg aan de Geul', 'Urk', 'Utrecht', 'Vaals', 'Utrechtse Heuvelrug', 'Uithoorn', 'Tytsjerksteradiel', 'Uitgeest', 'Tynaarlo', 'Twenterand', 'Tilburg', 'Tubbergen', 'Teylingen', 'Den Haag', 'Tiel', 'Tholen', 'Súdwest-Fryslân', 'Terschellin

In [23]:
df = pd.read_csv('/Users/datoapanta/Desktop/autopop/context-match/databases/Locations - Netherlands.csv')
col_names = list(df.columns)
sample = df.sample(n=5, random_state=42)

#print the sample
print(sample)

desc = f"The name of the table is 'Locations - Netherlands'. It has these columns: {col_names}. This is a extract from the table:\n"

for sample_value in range(len(sample)):
    for col_name in col_names:
            desc += f"{col_name}: {sample[col_name].values[sample_value]}\n"

print(desc)

    Municipality                         Neighboring Municipalities  CBS Code  \
237       Goirle  Gilze en Rijen, Tilburg, Alphen-Chaam, Ravels,...     785.0   
116    Purmerend  Alkmaar, Koggenland, Edam-Volendam, Wormerland...     439.0   
113       Putten   Zeewolde, Nuldernauw, Ermelo, Nijkerk, Barneveld     273.0   
42      Vlieland                     Terschelling, Harlingen, Texel      96.0   
126       Opmeer  Hollands Kroon, Medemblik, Dijk en Waard, Kogg...     432.0   

          Province  
237  North Brabant  
116  North Holland  
113     Gelderland  
42       Friesland  
126  North Holland  
The name of the table is 'Locations - Netherlands'. It has these columns and entry samples:
Municipality: Goirle
Neighboring Municipalities: Gilze en Rijen, Tilburg, Alphen-Chaam, Ravels, Hilvarenbeek
CBS Code: 785.0
Province: North Brabant
Municipality: Purmerend
Neighboring Municipalities: Alkmaar, Koggenland, Edam-Volendam, Wormerland, Landsmeer, Waterland
CBS Code: 439.0
Province:

In [21]:
df.head()

Municipality                         Neighboring Municipalities  \
0           Zwolle  Kampen, Zwartewaterland, Staphorst, Hattem, Da...   
1  Zwartewaterland  Noordoostpolder, Steenwijkerland, Kampen, Stap...   
2      Zwijndrecht  Barendrecht, Ridderkerk, Hendrik-Ido-Ambacht, ...   
3         Zuidplas  Alphen aan den Rijn, Gouda (hoofdbetekenis), W...   
4          Zutphen  Voorst, Lochem, Brummen, Bronckhorst (hoofdbet...   

   CBS Code       Province  
0     193.0     Overijssel  
1    1896.0     Overijssel  
2     642.0  South Holland  
3    1892.0  South Holland  
4     301.0     Gelderland

In [25]:
import itertools

def generate_pairs(input_dict):
    keys = list(input_dict.keys())
    pairs = list(itertools.combinations(keys, 2))
    return pairs

# Example dictionary
example_dict = {
    'item1': 'value1',
    'item2': 'value2',
    'item3': 'value3',
    # 'item4': 'value4'
}

# Generate pairs
pairs = generate_pairs(example_dict)
print(pairs)


[('item1', 'item2'), ('item1', 'item3'), ('item2', 'item3')]


In [ ]:
(0,0) = 0,73
(0,1) = 0.73

stdv ^
(0,2) = 0.3 
(0,20)= 0.01

"""
pool of candidate = high score

txt matching: fuzzy match, 
"""


In [4]:
import pandas as pd
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [30, 25, 35]
}
df = pd.DataFrame(data)

In [10]:
for k, rows in df.iterrows():   
    print(rows.)

0
1
2
