In [6]:
import numpy as np

# create two random arrays of the same size
x = np.random.rand(5)
y = np.random.rand(5)

print(x)
print(y)

from scipy.spatial.distance import cdist
from sentence_transformers import util

# compute the cosine distance between the two arrays using cdist
cosine_distance = 1 - cdist(x[:, None], y[:, None], metric='cosine')
print(cosine_distance)

# compute the cosine distance between the two arrays using sentence_transformers
cosine_distance_st = util.pytorch_cos_sim(x[:, None], y[:, None])
print(cosine_distance_st)

print(np.allclose(cosine_distance, cosine_distance_st.cpu().numpy()))


[0.61635501 0.47326762 0.87696553 0.23840527 0.53291692]
[0.52412417 0.71245148 0.4799476  0.75362221 0.93728032]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
True


In [9]:
import numpy as np
from scipy.spatial.distance import cdist
from sentence_transformers import util

# Create two random 2D arrays of shape (5, 10) to have more than one dimension
x = np.random.rand(5, 10)
y = np.random.rand(5, 10)

# Compute the cosine distance between the two arrays using cdist
cosine_distance = cdist(x, y, metric='cosine')

# Convert cosine distance to cosine similarity
cosine_similarity_cdist = 1 - cosine_distance

# Compute the cosine similarity between the two arrays using sentence_transformers
cosine_similarity_st = util.pytorch_cos_sim(x, y)

# Print the results
print("Cosine similarity using scipy's cdist:\n", cosine_similarity_cdist)
print("Cosine similarity using sentence_transformers' pytorch_cos_sim:\n", cosine_similarity_st)

# Compare the results
comparison = np.isclose(cosine_similarity_cdist, cosine_similarity_st.numpy(), atol=1e-6)
print("Are the results approximately equal?\n", comparison.all())


Cosine similarity using scipy's cdist:
 [[0.76785282 0.72877287 0.73773856 0.68076054 0.57399827]
 [0.61634297 0.74934921 0.96000236 0.96592665 0.75205659]
 [0.5885976  0.87679951 0.67979463 0.78676642 0.6989256 ]
 [0.7576953  0.78866301 0.73402599 0.82553025 0.67465421]
 [0.53237274 0.81621932 0.6576293  0.68680345 0.61133636]]
Cosine similarity using sentence_transformers' pytorch_cos_sim:
 tensor([[0.7679, 0.7288, 0.7377, 0.6808, 0.5740],
        [0.6163, 0.7493, 0.9600, 0.9659, 0.7521],
        [0.5886, 0.8768, 0.6798, 0.7868, 0.6989],
        [0.7577, 0.7887, 0.7340, 0.8255, 0.6747],
        [0.5324, 0.8162, 0.6576, 0.6868, 0.6113]], dtype=torch.float64)
Are the results approximately equal?
 True


In [11]:
# create a dataframe with some random text
import pandas as pd

df = pd.read_csv('/Users/datoapanta/Desktop/autopop/context-match/databases/Locations - Netherlands.csv')
print(df['Municipality'].astype(str).tolist())

['Zwolle', 'Zwartewaterland', 'Zwijndrecht', 'Zuidplas', 'Zutphen', 'Zundert', 'Zevenaar', 'Zeist', 'Zoeterwoude', 'Zoetermeer', 'Zandvoort', 'Zeewolde', 'Zaltbommel', 'Woerden', 'Woudenberg', 'Zaanstad', 'Wormerland', 'Winterswijk', 'Woensdrecht', 'Wijk bij Duurstede', 'Wijdemeren', 'Wijchen', 'Weststellingwerf', 'Wierden', 'Westerveld', 'Westervoort', 'Westerwolde', 'Westland', 'Weert', 'West Maas en Waal', 'Westerkwartier', 'West Betuwe', 'Wassenaar', 'Waterland', 'Wageningen', 'Waddinxveen', 'Waalwijk', 'Waadhoeke', 'Waalre', 'Voorst', 'Voorschoten', 'Vught', 'Vlieland', 'Voerendaal', 'Voorne aan Zee', 'Vlissingen', 'Vijfheerenlanden', 'Venray', 'Vlaardingen', 'Veere', 'Venlo', 'Velsen', 'Veldhoven', 'Veendam', 'Valkenswaard', 'Veenendaal', 'Valkenburg aan de Geul', 'Urk', 'Utrecht', 'Vaals', 'Utrechtse Heuvelrug', 'Uithoorn', 'Tytsjerksteradiel', 'Uitgeest', 'Tynaarlo', 'Twenterand', 'Tilburg', 'Tubbergen', 'Teylingen', 'Den Haag', 'Tiel', 'Tholen', 'Súdwest-Fryslân', 'Terschellin